# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/jwttest?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: mysql@weijie
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true
#
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG

management:
  security:
    enabled: false
  context-path: /actuator